# Um an den Autoconfiguration-Report zu kommen, reicht es die Anwendung mit
# einem debug-Flag zu starten

# java -jar xxx.jar --debug // Anwendungsparameter

# java -Ddebug=true -jar xxx.jar // JVM-Parameter

# als Umgebungsvariable würde auch noch gehen
# export DEBUG=true in einer Shell

# oder wie hier gewählt als Umgebungsparameter


debug: false # default ist false

# Actuator: der Actuator ist "Secure by Default" Informationen, die nach
# außen gegeben werden sollen, müssen speziell aktiviert werden:
management:
  endpoints:
    web:
      exposure:
        include: env, info, health, beans, conditions, configprops, heapdump, loggers, mappings, metrics, threaddump
  endpoint:
    health:
      # alle Details werden vom Aktuator herausgegeben
      show-details: always # daneben gibt es never und when_authorized


gruss:
  morgens: guten Morgen
  mittags: guten Tag
  abends: guten Abend
  abhaengigkeit:
    a-morgens: ${gruss.morgens}, es gibt Frühstück
    a-mittags: ${gruss.mittags}, es gibt Mittagessen
    a-abends: ${gruss.abends}, es gibt Abendessen

confprops:
  greetingMorgen: guten Morgen aus den Configproperties
  greetingMittag: guten Tag aus den Configproperties
  greetingAbend: guten Abend aus den Configproperties
